/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class DejaDb {
  constructor(path: string, ns?: string | undefined | null, passphrase?: string | undefined | null, actor?: string | undefined | null, telemetry?: string | undefined | null, principal?: string | undefined | null, indexText?: boolean | undefined | null)
  /**
   * Release this handle's claim on the memory file.
   *
   * One memory is one writer: a second handle on the same file is refused at
   * open. Rust and Python release on drop, but Node's is whenever GC runs —
   * so without this there is no way to say "I am done with this file" and
   * reopen it in the same process. Calling a method afterwards is an error,
   * not a silent reopen. Idempotent; in-flight async calls finish first.
   */
  close(): void
  /**
   * Reconciliation warnings from open (file-vs-host declaration changes,
   * embedding-model mismatches). JSON list string.
   */
  openWarnings(): Promise<string>
  /**
   * Install a command embedder (same contract as the CLI's --embed-cmd):
   * the command gets the text on stdin and must print a JSON array of
   * numbers. Probed once here to learn the dimension. Enables the vector
   * recall leg; grains added afterwards are embedded. (For an
   * in-process callback embedder, see `setEmbedder`; the command
   * embedder remains the zero-dependency path.)
   */
  setEmbedderCommand(cmd: string, model?: string | undefined | null): Promise<void>
  /**
   * Install an embedding callback: `embed(text: string): number[]` —
   * the JS mirror of Python's `set_embedder`. Probed once here (on the
   * JS thread) to learn the dimension, recorded as the file's embedding
   * provenance; store-side embeds run on worker threads and call back
   * through a threadsafe function.
   */
  setEmbedder(embed: (arg: string) => Array<number>, model?: string | undefined | null): void
  /**
   * Batch-add grains in ONE write transaction — the JS mirror of
   * Python's `add_batch`. `grainsJson` is a JSON array of
   * `{grain_type|type, fields}` objects; returns a JSON array of
   * hashes. Worth ~1.6x over one-at-a-time `add()`, and only with the
   * BM25 text index off (with it on, per-row index cost swamps
   * batching).
   */
  addBatch(grainsJson: string, ns?: string | undefined | null): Promise<string>
  /**
   * Free-text recall over the BM25 (and vector, when an embedder is
   * installed) legs — the JS mirror of Python's `search`, the same path
   * as `deja search` and CAL's `RECALL … ABOUT`. Returns a JSON list
   * string shaped like `recall()`. Errors loudly when the file has
   * neither leg, instead of a silent empty list.
   */
  search(query: string, subject?: string | undefined | null, relation?: string | undefined | null, k?: number | undefined | null, ns?: string | undefined | null): Promise<string>
  /**
   * Backfill + rebuild the BM25 text index (e.g. after bulk loads, or on
   * a file that flipped text indexing on later). Returns rows backfilled.
   */
  reindexText(): Promise<number>
  /**
   * Rebuild the link indexes: reverse provenance, run correlation, and
   * `related_to` cross-links. Returns index rows written.
   *
   * `open()` heals a file that predates these indexes, so this is for
   * rebuilding on demand — the counterpart of `reindexText()`, and what
   * `deja reindex` runs.
   */
  reindexLinks(): Promise<number>
  /**
   * Anthropic memory-tool command (view/create/str_replace/insert/delete/
   * rename over /memories): pass the tool-call object as JSON; returns the
   * tool result text. Wire this as your memory-tool backend.
   */
  memoryTool(commandJson: string, ns?: string | undefined | null): Promise<string>
  /**
   * Import another memory system's export. `source`: mem0 | mem0-history |
   * langgraph | letta | letta-archival | zep | jsonl. `payload` is the
   * export file's contents; `history` the optional mem0 history payload.
   * (basic-memory vault directories import via the CLI: `deja migrate`.)
   * Returns {added, superseded, forgotten, skipped, notes} as JSON.
   * Re-runs skip what is already imported.
   */
  migrate(source: string, payload: string, history?: string | undefined | null, ns?: string | undefined | null): Promise<string>
  /**
   * Add a Fact. Returns the content address (64-hex).
   * Add a Fact. With `idempotent = true`, a re-add of the value already at
   * the `(subject, relation)` head writes nothing and returns the existing
   * hash (value-level dedup, not just byte-identical replay).
   */
  addFact(subject: string, relation: string, object: string, confidence?: number | undefined | null, ns?: string | undefined | null, idempotent?: boolean | undefined | null): Promise<string>
  /** Add any grain type from a JSON fields object. Returns the hash. */
  add(grainType: string, fieldsJson: string, ns?: string | undefined | null): Promise<string>
  /** Structural recall, newest-first. Returns a JSON list string. */
  recall(subject: string, relation?: string | undefined | null, k?: number | undefined | null, ns?: string | undefined | null): Promise<string>
  /** Current head for (subject, relation) — JSON string or null. */
  latest(subject: string, relation: string, ns?: string | undefined | null): Promise<string | null>
  /** Supersede old_hash with a new version (append-only evolution). */
  supersede(oldHash: string, grainType: string, fieldsJson: string, ns?: string | undefined | null): Promise<string>
  /** Erase a grain from the hot store (tombstoned). Host-level op. */
  forget(hash: string): Promise<void>
  /**
   * Right-to-erasure for one identity: erase every grain holding a
   * STRUCTURED reference to `subject` in the session namespace (or `ns`) —
   * the full supersession history, grains referencing it in object
   * position, its thread events, its dictionary entry, and erased-only
   * vocabulary — with replicating tombstones. Resolves to the erasure
   * report as JSON (counts only, no identity material). Host-level
   * destructive op: gate it like your other compliance endpoints. See
   * docs/erasure.md for the scope contract.
   * Identity matching always covers partition-style keys (`pat`,
   * `pat#visit1` — never `patricia`); pass `textMentions=true` to ALSO
   * erase grains whose indexed text mentions the identity's tokens
   * (search symmetry — opt-in because token matching over-reaches for
   * common-word identifiers).
   */
  forgetSubject(subject: string, ns?: string | undefined | null, textMentions?: boolean | undefined | null): Promise<string>
  /**
   * Retention sweep: erase every grain with `created_at` older than
   * `cutoffMs` (epoch milliseconds), optionally limited to one grain type
   * (e.g. "event") and scoped to the session namespace (or `ns`; pass
   * ns="" to sweep every namespace). Resolves to the report JSON.
   */
  forgetOlderThan(cutoffMs: number, ns?: string | undefined | null, grainType?: string | undefined | null): Promise<string>
  /**
   * remember(): store content as an Event, then attach the facts
   * distilled from it. Three routes to those facts, in precedence order:
   * `factsJson` (pre-extracted by the host — a JSON list of
   * {subject, relation, object, confidence}), `llmCmd` (a subprocess
   * backend), or `model` ("openai:gpt-4o-mini", key from the env).
   *
   * The raw text is written before the model is called, so a failed
   * extraction never costs the raw text — the error names the hash it was
   * stored under. Model-extracted facts are stamped
   * `verification_status="unverified"` unless `groundModel`/`groundCmd`
   * runs a separate entailment pass (proposer ≠ scorer); facts it does not
   * support are dropped and survivors are stamped `"verified"`.
   *
   * The raw text is stored as an **Event** grain (a transcript turn) —
   * pass `sessionId`/`role` to place it in a conversation thread.
   *
   * Returns {"event", "facts"} JSON, plus {"model", "proposed",
   * "dropped", "verification_status"} when a model ran.
   */
  remember(content: string, factsJson?: string | undefined | null, observer?: string | undefined | null, ns?: string | undefined | null, model?: string | undefined | null, llmCmd?: string | undefined | null, groundModel?: string | undefined | null, groundCmd?: string | undefined | null, extractHint?: string | undefined | null, minConfidence?: number | undefined | null, sessionId?: string | undefined | null, role?: string | undefined | null, runId?: string | undefined | null): Promise<string>
  /**
   * Execute CAL. Returns the wire-format payload as a JSON string.
   * Non-fatal `CAL-Wnnn` warnings ride along under a `warnings` key
   * (absent when the query raised none).
   */
  cal(query: string): Promise<string>
  /** Supersession-chain history for (subject, relation), newest first. */
  history(subject: string, relation: string, ns?: string | undefined | null): Promise<string>
  /**
   * Reverse provenance: grains distilled from `sourceHash` (their
   * `derived_from`), newest first, as a JSON list string.
   */
  provenance(sourceHash: string): Promise<string>
  /**
   * Advise-mode novelty check: nearest existing grains to `text`, optionally
   * scoped to (subject, relation), as a JSON list of {hash, similarity},
   * most similar first. Requires an installed embedder; never writes.
   */
  nearest(text: string, subject?: string | undefined | null, relation?: string | undefined | null, k?: number | undefined | null, ns?: string | undefined | null): Promise<string>
  /** Store statistics as JSON. */
  stats(): Promise<string>
  /** Incremental backup to a bundle file. Returns last_op_seq cursor. */
  bundle(path: string, since?: number | undefined | null): Promise<number>
  /** Apply a bundle (fast-forward, idempotent). Returns ops applied. */
  importBundle(path: string): Promise<number>
  /** Integrity + content-address verification. Throws on failure. */
  verify(): Promise<string>
  /**
   * Bounded k-hop walk over the entity graph.
   *
   * `relations` is comma-separated. `direction` is out|in|both — in/both use
   * the reverse index, which only covers relations the file declares
   * entity-valued, so they find nothing for relations outside that set.
   *
   * Argument validation happens inside the task so a bad `direction` or an
   * empty relation list *rejects* the promise, matching every other method
   * here — throwing synchronously would contradict the `Promise<string>`
   * signature napi generates.
   */
  related(start: string, relations: string, direction?: string | undefined | null, depth?: number | undefined | null, limit?: number | undefined | null, ns?: string | undefined | null): Promise<string>
  /**
   * As-of read on two axes: `world` = what was true at `at`,
   * `knowledge` = what the agent knew at `at`. `at` is epoch milliseconds.
   */
  entityAt(subject: string, relation: string, at: number, axis?: string | undefined | null, ns?: string | undefined | null): Promise<string>
  /**
   * What a run recorded, and what it produced downstream.
   *
   * Returns `{run_id, trace, produced}` — `trace` is the run's own grains,
   * `produced` is what was derived from them and is not itself part of the
   * run. This is the query that crosses from execution history into
   * semantic memory.
   */
  runTrace(runId: string, limit?: number | undefined | null, includeYield?: boolean | undefined | null, ns?: string | undefined | null): Promise<string>
  /**
   * Which runs produced or refined this grain — the reverse join.
   *
   * Runs that merely *read* the grain are not recorded: a read leaves no
   * grain behind, so nothing in an append-only store can attest to it.
   */
  runsTouching(hash: string, depth?: number | undefined | null, ns?: string | undefined | null): Promise<string>
  /**
   * Execution records for a workflow: which grains ran which of its nodes.
   *
   * A Workflow grain is immutable, so runs point at the plan rather than
   * mutating it — retries show up as several records for one node.
   */
  stepActions(workflow: string, node?: string | undefined | null, limit?: number | undefined | null, ns?: string | undefined | null): Promise<string>
  /**
   * Record a tool call as a Tool grain — the flagship analyzer's food.
   *
   * `callId` is the invocation's own id (the provider's `tool_call_id`),
   * stored on the grain and queryable — the correlation key back to the LLM
   * transcript. Omitted, one is synthesized. Either way each call is its own
   * occurrence, which is what makes a tool that failed five times read as
   * five failures; recording is append-only, never de-duplicating.
   */
  recordToolCall(name: string, result: string, isError?: boolean | undefined | null, thread?: string | undefined | null, callId?: string | undefined | null): Promise<string>
  /**
   * Run one analysis pass. Bare it never gates. `fullSweep` re-analyzes
   * the whole memory (`deja loop reflect` semantics); `policy` is a path
   * to a host `loop-policy.json` — the only way auto-apply is granted
   * from the bindings. Returns run-outcome JSON.
   */
  loopRun(minNew?: number | undefined | null, minNewErrors?: number | undefined | null, ifStale?: string | undefined | null, model?: string | undefined | null, llmCmd?: string | undefined | null, groundModel?: string | undefined | null, groundCmd?: string | undefined | null, analyzerCmd?: string | undefined | null, fullSweep?: boolean | undefined | null, policy?: string | undefined | null): Promise<string>
  /**
   * List recommendations. `filter` is optional JSON, e.g. `{"status":
   * "pending"}`; `{"status":"all"}` clears the filter. JSON list.
   */
  recommendations(filter?: string | undefined | null): Promise<string>
  /**
   * Approve and apply a recommendation in one audited step (§6.6). The
   * `because` reason is mandatory. A refused apply leaves the recommendation
   * **pending**, so it can still be dismissed.
   *
   * `scopes` is a comma-separated subset of `read,write,review,apply,admin`;
   * omit it for all scopes.
   */
  applyRecommendation(hash: string, because: string, allowDestructive?: boolean | undefined | null, scopes?: string | undefined | null): Promise<string>
  /**
   * Approve a recommendation **without** applying it — the two-person flow
   * the CLI's separate `approve` verb enables, so a supervising agent can
   * approve for a human to apply later.
   */
  approveRecommendation(hash: string, because: string, scopes?: string | undefined | null): Promise<string>
  /**
   * Health snapshot of the loop: when it last ran, how much is un-analyzed
   * since, the queue counts, and whether it looks stalled. Parity with bare
   * `deja loop` and `GET /api/loop/health`.
   */
  loopHealth(): Promise<string>
  /** The analyzer roster: id, whether it is enabled, and its settings. */
  loopAnalyzers(): Promise<string>
  /**
   * Enable/disable one analyzer, or set its parameters — reachable from the
   * console's Setup tab (`POST /api/loop/config`) but not, until now, from
   * the bindings. `paramsJson` is an optional JSON object of overrides.
   */
  setAnalyzerConfig(analyzerId: string, enabled?: boolean | undefined | null, paramsJson?: string | undefined | null): Promise<string>
  /** Reject a recommendation with a reason (library-friendly `reject`). */
  dismissRecommendation(hash: string, why: string, scopes?: string | undefined | null): Promise<string>
  /**
   * Roll back an applied recommendation (retracts the grains it created).
   * Mandatory reason; fails for non-rollbackable applies (FORGET has no
   * inverse). Parity with `deja loop rollback`.
   */
  rollbackRecommendation(hash: string, because: string): Promise<string>
  /**
   * Measured outcomes of applied recommendations — the Verify gate's
   * record (`held` / `regressed` per checkpoint). JSON list, parity with
   * `deja loop outcomes`.
   */
  loopOutcomes(): Promise<string>
}

/**
 * Drop a memory schema entirely — the postgres backend's memory-level
 * erasure primitive (`DROP SCHEMA … CASCADE`), the analogue of deleting a
 * memory file. Destroys the memory AND its telemetry/blobs. Admin surface:
 * gate it like any destructive operation in your host.
 */
export declare function dropPostgresSchema(url: string, schema: string): void
