/* auto-generated by NAPI-RS */
/* eslint-disable */
/** One memory = one file. Open with `new DejaDb("caller.db", "caller")`. */
export declare class DejaDb {
  constructor(path: string, ns?: string | undefined | null, passphrase?: string | undefined | null, actor?: string | undefined | null)
  /**
   * Reconciliation warnings from open (file-vs-host declaration changes,
   * embedding-model mismatches). JSON list string.
   */
  openWarnings(): string
  /**
   * Install a command embedder (same contract as the CLI's --embed-cmd):
   * the command gets the text on stdin and must print a JSON array of
   * numbers. Probed once here to learn the dimension. Enables the vector
   * recall leg; grains added afterwards are embedded. (An in-process JS
   * callback embedder needs an async surface — planned; the command
   * embedder is the stable path today.)
   */
  setEmbedderCommand(cmd: string, model?: string | undefined | null): void
  /**
   * Backfill + rebuild the BM25 text index (e.g. after bulk loads, or on
   * a file that flipped text indexing on later). Returns rows backfilled.
   */
  reindexText(): number
  /**
   * Anthropic memory-tool command (view/create/str_replace/insert/delete/
   * rename over /memories): pass the tool-call object as JSON; returns the
   * tool result text. Wire this as your memory-tool backend.
   */
  memoryTool(commandJson: string, ns?: string | undefined | null): string
  /**
   * Import another memory system's export. `source`: mem0 | mem0-history |
   * langgraph | letta | letta-archival | zep | jsonl. `payload` is the
   * export file's contents; `history` the optional mem0 history payload.
   * (basic-memory vault directories import via the CLI: `deja migrate`.)
   * Returns {added, superseded, forgotten, skipped, notes} as JSON.
   * Re-runs skip what is already imported.
   */
  migrate(source: string, payload: string, history?: string | undefined | null, ns?: string | undefined | null): string
  /**
   * Add a Fact. Returns the content address (64-hex).
   * Add a Fact. With `idempotent = true`, a re-add of the value already at
   * the `(subject, relation)` head writes nothing and returns the existing
   * hash (value-level dedup, not just byte-identical replay).
   */
  addFact(subject: string, relation: string, object: string, confidence?: number | undefined | null, ns?: string | undefined | null, idempotent?: boolean | undefined | null): string
  /** Add any grain type from a JSON fields object. Returns the hash. */
  add(grainType: string, fieldsJson: string, ns?: string | undefined | null): string
  /** Structural recall, newest-first. Returns a JSON list string. */
  recall(subject: string, relation?: string | undefined | null, k?: number | undefined | null, ns?: string | undefined | null): string
  /** Current head for (subject, relation) — JSON string or null. */
  latest(subject: string, relation: string, ns?: string | undefined | null): string | null
  /** Supersede old_hash with a new version (append-only evolution). */
  supersede(oldHash: string, grainType: string, fieldsJson: string, ns?: string | undefined | null): string
  /** Erase a grain from the hot store (tombstoned). Host-level op. */
  forget(hash: string): void
  /**
   * remember(): store content as an Observation; optional pre-extracted
   * facts (JSON list of {subject, relation, object, confidence}) become
   * provenance-linked Facts. Returns {"observation", "facts"} JSON.
   */
  remember(content: string, factsJson?: string | undefined | null, observer?: string | undefined | null, ns?: string | undefined | null): string
  /** Execute CAL. Returns the wire-format payload as a JSON string. */
  cal(query: string): string
  /** Supersession-chain history for (subject, relation), newest first. */
  history(subject: string, relation: string, ns?: string | undefined | null): string
  /**
   * Reverse provenance: grains distilled from `sourceHash` (their
   * `derived_from`), newest first, as a JSON list string.
   */
  provenance(sourceHash: string): string
  /**
   * Advise-mode novelty check: nearest existing grains to `text`, optionally
   * scoped to (subject, relation), as a JSON list of {hash, similarity},
   * most similar first. Requires an installed embedder; never writes.
   */
  nearest(text: string, subject?: string | undefined | null, relation?: string | undefined | null, k?: number | undefined | null, ns?: string | undefined | null): string
  /** Store statistics as JSON. */
  stats(): string
  /** Incremental backup to a bundle file. Returns last_op_seq cursor. */
  bundle(path: string, since?: number | undefined | null): number
  /** Apply a bundle (fast-forward, idempotent). Returns ops applied. */
  importBundle(path: string): number
  /** Integrity + content-address verification. Throws on failure. */
  verify(): string
  /** Record a tool call as a Tool grain — the flagship analyzer's food. */
  recordToolCall(name: string, result: string, isError?: boolean | undefined | null, thread?: string | undefined | null): string
  /** Run one analysis pass. Bare it never gates. Returns run-outcome JSON. */
  waiserRun(minNew?: number | undefined | null, minNewErrors?: number | undefined | null, ifStale?: string | undefined | null): string
  /**
   * List recommendations. `filter` is optional JSON, e.g. `{"status":
   * "pending"}`; `{"status":"all"}` clears the filter. JSON list.
   */
  recommendations(filter?: string | undefined | null): string
  /**
   * Approve and apply a recommendation in one audited step (§6.6). The
   * `because` reason is mandatory.
   */
  applyRecommendation(hash: string, because: string, allowDestructive?: boolean | undefined | null): string
  /** Reject a recommendation with a reason (library-friendly `reject`). */
  dismissRecommendation(hash: string, why: string): string
}
